---
default_values:
  editor_snap_size: 1
  killzone: null
  endzone: null
  scene: null # This is so that a block may be a scene instead of a model
---
block_overrides:
  example_block:
    editor_snap_size: 0.1
    killzone:
      object: ExampleBlockKillzone.obj